"""Correctness tests for survival model adapters against analytical ground truth
and R marginaleffects reference values.

These tests verify that pymargins produces mathematically correct point estimates
for survival model predictions and marginal effects.

Notes on scale differences
--------------------------
- R marginaleffects ``predictions(type='risk')`` for Cox PH returns *centered*
  relative risk: exp(Xβ - mean(Xβ)). Our PHReg adapter returns raw hazard
  ratios exp(Xβ). Our lifelines CoxPH adapter returns centered partial hazards
  exp((X - X_mean)β), matching marginaleffects.

- R marginaleffects ``predictions(type='response')`` for Weibull AFT (survreg)
  returns mean survival time. Our Weibull adapter predicts survival probability
  S(t|x) at a fixed time. These are different scales, so we compare against
  manually computed S(t|x) values.

Reference values
----------------
R marginaleffects reference values were generated by::

    Rscript tests/_generate_survival_reference.R

and are hard-coded below. The R script uses the survival and marginaleffects
packages with seed=42 and n=200.
"""

import jax
jax.config.update("jax_enable_x64", True)

import jax.numpy as jnp
import numpy as np
import pandas as pd
import pytest
pytest.importorskip("lifelines")
from statsmodels.duration.hazard_regression import PHReg
from lifelines import CoxPHFitter, WeibullAFTFitter

from pymargins._adapters.statsmodels_phreg import StatsmodelsPHRegAdapter
from pymargins._adapters.lifelines_coxph import LifelinesCoxPHAdapter
from pymargins._adapters.lifelines_weibull_aft import LifelinesWeibullAFTAdapter
from pymargins import Margins


# ---------------------------------------------------------------------------
# Shared data and reference values
# ---------------------------------------------------------------------------

# Generated from R with set.seed(42), n=200
# The data is hard-coded so tests are reproducible without R installed.
# To regenerate, run:  python -m pytest tests/test_correctness_survival.py -v
# (the fixture below loads from the same CSV that R wrote)

# R marginaleffects reference values for Cox PH (type='risk', centered)
R_COX_PREDICTIONS = np.array([
    2.4117432289, 0.8161434690, 0.7631968846, 0.6169463370, 1.6514428206
])
R_COX_AME_X1 = 0.2114106
R_COX_AME_X2 = -0.3195936

# Manual analytical AMEs for raw (uncentered) hazard ratio scale
MANUAL_PHREG_AME_X1 = 0.20955182966947716
MANUAL_PHREG_AME_X2 = -0.31678367693654086

# Weibull AFT reference (manual analytical)
MANUAL_WEIBULL_SURV_PROBS = np.array([
    0.3058085, 0.6488832, 0.6632869, 0.7124786, 0.4357468
])
MANUAL_WEIBULL_AME_X1 = -0.05793763
MANUAL_WEIBULL_AME_X2 = 0.08307657


@pytest.fixture(scope="module")
def df_survival():
    """Load the exact same data used for R reference values."""
    # Try to load from the R-generated CSV first
    import os
    csv_path = "/tmp/survival_data.csv"
    if os.path.exists(csv_path):
        return pd.read_csv(csv_path)
    # Fallback: regenerate in Python with the same RNG sequence
    # (R's rnorm with seed=42 produces different values than numpy,
    # so the CSV is the preferred source)
    rng = np.random.default_rng(42)
    n = 200
    df = pd.DataFrame({
        "x1": rng.standard_normal(n),
        "x2": rng.standard_normal(n),
    })
    hazard = np.exp(0.5 + 0.3 * df["x1"] - 0.2 * df["x2"])
    df["time"] = rng.exponential(1.0 / hazard)
    df["status"] = (rng.random(n) < 0.8).astype(int)
    return df


# ---------------------------------------------------------------------------
# 1. Statsmodels PHReg (raw hazard ratio scale)
# ---------------------------------------------------------------------------

def test_phreg_predictions_match_analytical(df_survival):
    """PHReg predict() should return raw exp(X @ beta)."""
    fit = PHReg(
        df_survival["time"].values,
        df_survival[["x1", "x2"]].values,
        status=df_survival["status"].values,
    ).fit()
    adapter = StatsmodelsPHRegAdapter(fit, training_data=df_survival)

    X5 = adapter.design_matrix_from_df(df_survival.head(5))
    pred = np.asarray(adapter.predict(adapter.coefficients(), X5))

    # Manual computation
    beta = fit.params
    X = df_survival[["x1", "x2"]].head(5).values
    manual = np.exp(X @ beta)

    np.testing.assert_allclose(pred, manual, rtol=1e-10)


def test_phreg_predictions_differ_from_centered_risk(df_survival):
    """Raw HR predictions differ from marginaleffects' centered risk by ~1%."""
    fit = PHReg(
        df_survival["time"].values,
        df_survival[["x1", "x2"]].values,
        status=df_survival["status"].values,
    ).fit()
    adapter = StatsmodelsPHRegAdapter(fit, training_data=df_survival)

    X5 = adapter.design_matrix_from_df(df_survival.head(5))
    pred = np.asarray(adapter.predict(adapter.coefficients(), X5))

    # R marginaleffects type='risk' is centered at the mean
    # The ratio should be roughly constant = exp(-mean(X @ beta))
    mean_lp = np.mean(df_survival[["x1", "x2"]].values @ fit.params)
    centered_manual = np.exp(df_survival[["x1", "x2"]].head(5).values @ fit.params - mean_lp)

    np.testing.assert_allclose(pred / centered_manual, np.exp(mean_lp), rtol=1e-10)


def test_phreg_ame_matches_analytical(df_survival):
    """AME on raw HR scale should match mean(beta * exp(X @ beta))."""
    fit = PHReg(
        df_survival["time"].values,
        df_survival[["x1", "x2"]].values,
        status=df_survival["status"].values,
    ).fit()
    adapter = StatsmodelsPHRegAdapter(fit, training_data=df_survival)
    # Use identity scale for dydx (marginal effects can be negative)
    m = Margins(fit, adapter=adapter)

    res_x1 = m.dydx("x1")
    res_x2 = m.dydx("x2")

    # Analytical ground truth
    X = df_survival[["x1", "x2"]].values
    pred_all = np.exp(X @ fit.params)
    manual_ame_x1 = np.mean(fit.params[0] * pred_all)
    manual_ame_x2 = np.mean(fit.params[1] * pred_all)

    np.testing.assert_allclose(float(res_x1.estimate), manual_ame_x1, rtol=1e-5)
    np.testing.assert_allclose(float(res_x2.estimate), manual_ame_x2, rtol=1e-5)


# ---------------------------------------------------------------------------
# 2. Lifelines CoxPH (centered partial hazard scale)
# ---------------------------------------------------------------------------

def _skip_if_no_r_data():
    import os
    if not os.path.exists("/tmp/survival_data.csv"):
        pytest.skip("R-generated survival data CSV not found; skipping R reference comparison")


def test_coxph_predictions_match_marginaleffects(df_survival):
    """Lifelines CoxPH predictions should match R marginaleffects type='risk'."""
    _skip_if_no_r_data()
    fit = CoxPHFitter()
    fit.fit(df_survival, duration_col="time", event_col="status", formula="x1 + x2")
    adapter = LifelinesCoxPHAdapter(fit, training_data=df_survival)

    X5 = adapter.design_matrix_from_df(df_survival.head(5))
    pred = np.asarray(adapter.predict(adapter.coefficients(), X5))

    np.testing.assert_allclose(pred, R_COX_PREDICTIONS, rtol=1e-6)


def test_coxph_ame_matches_marginaleffects(df_survival):
    """AME on centered HR scale should match R marginaleffects avg_slopes."""
    _skip_if_no_r_data()
    fit = CoxPHFitter()
    fit.fit(df_survival, duration_col="time", event_col="status", formula="x1 + x2")
    adapter = LifelinesCoxPHAdapter(fit, training_data=df_survival)
    # Use identity scale for dydx (marginal effects can be negative)
    m = Margins(fit, adapter=adapter)

    res_x1 = m.dydx("x1")
    res_x2 = m.dydx("x2")

    np.testing.assert_allclose(float(res_x1.estimate), R_COX_AME_X1, rtol=1e-4)
    np.testing.assert_allclose(float(res_x2.estimate), R_COX_AME_X2, rtol=1e-4)


def test_coxph_ame_matches_analytical(df_survival):
    """AME on centered partial-hazard scale matches analytical derivative."""
    fit = CoxPHFitter()
    fit.fit(df_survival, duration_col="time", event_col="status", formula="x1 + x2")
    adapter = LifelinesCoxPHAdapter(fit, training_data=df_survival)
    m = Margins(fit, adapter=adapter)

    res_x1 = m.dydx("x1")
    res_x2 = m.dydx("x2")

    # Analytical AME for centered scale: mean(beta_j * exp((X - X_mean) @ beta))
    beta = fit.params_.values
    X = df_survival[["x1", "x2"]].values
    x_mean = fit._norm_mean.values
    pred_all = np.exp((X - x_mean) @ beta)
    manual_ame_x1 = np.mean(beta[0] * pred_all)
    manual_ame_x2 = np.mean(beta[1] * pred_all)

    np.testing.assert_allclose(float(res_x1.estimate), manual_ame_x1, rtol=1e-5)
    np.testing.assert_allclose(float(res_x2.estimate), manual_ame_x2, rtol=1e-5)


def test_coxph_predictions_match_lifelines(df_survival):
    """Adapter predict() should agree with lifelines' predict_partial_hazard."""
    fit = CoxPHFitter()
    fit.fit(df_survival, duration_col="time", event_col="status", formula="x1 + x2")
    adapter = LifelinesCoxPHAdapter(fit, training_data=df_survival)

    X5 = adapter.design_matrix_from_df(df_survival.head(5))
    our_pred = np.asarray(adapter.predict(adapter.coefficients(), X5))
    ll_pred = fit.predict_partial_hazard(df_survival[["x1", "x2"]].head(5)).values

    np.testing.assert_allclose(our_pred, ll_pred, rtol=1e-6)


# ---------------------------------------------------------------------------
# 3. Lifelines Weibull AFT (survival probability scale)
# ---------------------------------------------------------------------------

def test_weibull_predictions_match_analytical(df_survival):
    """Survival probabilities should match analytical S(t|x) formula."""
    fit = WeibullAFTFitter()
    fit.fit(df_survival, duration_col="time", event_col="status")
    adapter = LifelinesWeibullAFTAdapter(fit, training_data=df_survival)

    t_med = adapter._prediction_time
    beta = fit.params_
    beta_lambda = beta.loc["lambda_"].values
    beta_rho = beta.loc["rho_"].values
    rho = np.exp(beta_rho[0])

    X5 = np.asarray(adapter.design_matrix_from_df(df_survival.head(5)))
    lambda_x = np.exp(X5 @ beta_lambda)
    manual_S = np.exp(-(t_med / lambda_x) ** rho)

    pred = np.asarray(adapter.predict(adapter.coefficients(), X5))

    np.testing.assert_allclose(pred, manual_S, rtol=1e-6)


def test_weibull_ame_matches_analytical(df_survival):
    """AME on survival probability scale should match analytical derivative."""
    fit = WeibullAFTFitter()
    fit.fit(df_survival, duration_col="time", event_col="status")
    adapter = LifelinesWeibullAFTAdapter(fit, training_data=df_survival)
    # Identity scale is appropriate for survival probabilities (bounded [0,1])
    m = Margins(fit, adapter=adapter)

    res_x1 = m.dydx("x1")
    res_x2 = m.dydx("x2")

    # Analytical derivative: dS/dx_j = S * rho * (t/lambda)^rho * beta_lambda_j
    t_med = adapter._prediction_time
    beta = fit.params_
    beta_lambda = beta.loc["lambda_"].values
    beta_rho = beta.loc["rho_"].values
    rho = np.exp(beta_rho[0])

    X_all = np.asarray(adapter.design_matrix_from_df(df_survival))
    lambda_all = np.exp(X_all @ beta_lambda)
    S_all = np.exp(-(t_med / lambda_all) ** rho)

    manual_ame_x1 = np.mean(S_all * rho * (t_med / lambda_all) ** rho * beta_lambda[0])
    manual_ame_x2 = np.mean(S_all * rho * (t_med / lambda_all) ** rho * beta_lambda[1])

    np.testing.assert_allclose(float(res_x1.estimate), manual_ame_x1, rtol=1e-4)
    np.testing.assert_allclose(float(res_x2.estimate), manual_ame_x2, rtol=1e-4)


def test_weibull_predictions_match_lifelines(df_survival):
    """Adapter predict() should agree with lifelines predict_survival_function."""
    fit = WeibullAFTFitter()
    fit.fit(df_survival, duration_col="time", event_col="status")
    adapter = LifelinesWeibullAFTAdapter(fit, training_data=df_survival)

    t = adapter._prediction_time
    X5 = adapter.design_matrix_from_df(df_survival.head(5))
    our_pred = np.asarray(adapter.predict(adapter.coefficients(), X5))
    ll_pred = fit.predict_survival_function(
        df_survival[["x1", "x2"]].head(5), times=[t]
    ).values.flatten()

    np.testing.assert_allclose(our_pred, ll_pred, rtol=1e-6)


# ---------------------------------------------------------------------------
# 4. Lifelines CoxPH survival-probability scale
# ---------------------------------------------------------------------------

def test_coxph_survival_predictions_match_manual(df_survival):
    """S(t|x) = S_0(t) ^ PH(x) should match manual computation."""
    from pymargins._adapters.lifelines_coxph_survival import LifelinesCoxPHSurvivalAdapter
    fit = CoxPHFitter()
    fit.fit(df_survival, duration_col="time", event_col="status", formula="x1 + x2")
    adapter = LifelinesCoxPHSurvivalAdapter(fit, training_data=df_survival)

    t = adapter._prediction_time
    X5 = adapter.design_matrix_from_df(df_survival.head(5))
    pred = np.asarray(adapter.predict(adapter.coefficients(), X5))

    # Manual: S0(t) ^ PH(x)
    ph = fit.predict_partial_hazard(df_survival[["x1", "x2"]].head(5)).values.flatten()
    S0 = fit.baseline_survival_
    col = S0.columns[0]
    times = S0.index.values
    surv = S0[col].values
    if times[0] > times[-1]:
        times = times[::-1]
        surv = surv[::-1]
    S0_t = float(np.interp(t, times, surv))
    manual = S0_t ** ph

    np.testing.assert_allclose(pred, manual, rtol=1e-6)


def test_coxph_survival_predictions_match_lifelines(df_survival):
    """Adapter predict() should agree with lifelines predict_survival_function."""
    from pymargins._adapters.lifelines_coxph_survival import LifelinesCoxPHSurvivalAdapter
    fit = CoxPHFitter()
    fit.fit(df_survival, duration_col="time", event_col="status", formula="x1 + x2")
    adapter = LifelinesCoxPHSurvivalAdapter(fit, training_data=df_survival)

    t = adapter._prediction_time
    X5 = adapter.design_matrix_from_df(df_survival.head(5))
    our_pred = np.asarray(adapter.predict(adapter.coefficients(), X5))
    ll_pred = fit.predict_survival_function(
        df_survival[["x1", "x2"]].head(5), times=[t]
    ).values.flatten()

    np.testing.assert_allclose(our_pred, ll_pred, rtol=1e-6)


# ---------------------------------------------------------------------------
# 5. Statsmodels PHReg survival-probability scale
# ---------------------------------------------------------------------------

def test_phreg_survival_predictions_match_statsmodels(df_survival):
    """Adapter predict() should agree with statsmodels PHReg pred_type='surv'."""
    from pymargins._adapters.statsmodels_phreg_survival import StatsmodelsPHRegSurvivalAdapter
    fit = PHReg(
        df_survival["time"].values,
        df_survival[["x1", "x2"]].values,
        status=df_survival["status"].values,
    ).fit()
    adapter = StatsmodelsPHRegSurvivalAdapter(fit, training_data=df_survival)

    t = adapter._prediction_time
    X5 = adapter.design_matrix_from_df(df_survival.head(5))
    our_pred = np.asarray(adapter.predict(adapter.coefficients(), X5))

    sm_pred = fit.model.predict(
        fit.params,
        endog=np.full(5, t),
        exog=df_survival[["x1", "x2"]].head(5).values,
        pred_type="surv",
    )
    np.testing.assert_allclose(our_pred, sm_pred.predicted_values, rtol=1e-6)


# ---------------------------------------------------------------------------
# 6. Lifelines LogNormal AFT
# ---------------------------------------------------------------------------

def test_lognormal_predictions_match_analytical(df_survival):
    """S(t|x) = 1 - Φ((log(t) - μ) / σ) should match manual computation."""
    from lifelines import LogNormalAFTFitter
    from pymargins._adapters.lifelines_lognormal_aft import LifelinesLogNormalAFTAdapter

    fit = LogNormalAFTFitter()
    fit.fit(df_survival, duration_col="time", event_col="status")
    adapter = LifelinesLogNormalAFTAdapter(fit, training_data=df_survival)

    t = adapter._prediction_time
    X5 = np.asarray(adapter.design_matrix_from_df(df_survival.head(5)))
    pred = np.asarray(adapter.predict(adapter.coefficients(), X5))

    beta = fit.params_
    beta_mu = beta.loc["mu_"].values
    beta_sigma = beta.loc["sigma_"].values[0]
    mu = X5 @ beta_mu
    sigma = np.exp(beta_sigma)
    from scipy.stats import norm
    manual = 1.0 - norm.cdf((np.log(t) - mu) / sigma)

    np.testing.assert_allclose(pred, manual, rtol=1e-6)


def test_lognormal_predictions_match_lifelines(df_survival):
    """Adapter predict() should agree with lifelines predict_survival_function."""
    from lifelines import LogNormalAFTFitter
    from pymargins._adapters.lifelines_lognormal_aft import LifelinesLogNormalAFTAdapter

    fit = LogNormalAFTFitter()
    fit.fit(df_survival, duration_col="time", event_col="status")
    adapter = LifelinesLogNormalAFTAdapter(fit, training_data=df_survival)

    t = adapter._prediction_time
    X5 = adapter.design_matrix_from_df(df_survival.head(5))
    our_pred = np.asarray(adapter.predict(adapter.coefficients(), X5))
    ll_pred = fit.predict_survival_function(
        df_survival[["x1", "x2"]].head(5), times=[t]
    ).values.flatten()

    np.testing.assert_allclose(our_pred, ll_pred, rtol=1e-6)


# ---------------------------------------------------------------------------
# 7. Lifelines LogLogistic AFT
# ---------------------------------------------------------------------------

def test_loglogistic_predictions_match_analytical(df_survival):
    """S(t|x) = 1 / (1 + (t / α)^β) should match manual computation."""
    from lifelines import LogLogisticAFTFitter
    from pymargins._adapters.lifelines_loglogistic_aft import LifelinesLogLogisticAFTAdapter

    fit = LogLogisticAFTFitter()
    fit.fit(df_survival, duration_col="time", event_col="status")
    adapter = LifelinesLogLogisticAFTAdapter(fit, training_data=df_survival)

    t = adapter._prediction_time
    X5 = np.asarray(adapter.design_matrix_from_df(df_survival.head(5)))
    pred = np.asarray(adapter.predict(adapter.coefficients(), X5))

    beta = fit.params_
    beta_alpha = beta.loc["alpha_"].values
    beta_beta = beta.loc["beta_"].values[0]
    alpha = np.exp(X5 @ beta_alpha)
    beta_param = np.exp(beta_beta)
    manual = 1.0 / (1.0 + (t / alpha) ** beta_param)

    np.testing.assert_allclose(pred, manual, rtol=1e-6)


def test_loglogistic_predictions_match_lifelines(df_survival):
    """Adapter predict() should agree with lifelines predict_survival_function."""
    from lifelines import LogLogisticAFTFitter
    from pymargins._adapters.lifelines_loglogistic_aft import LifelinesLogLogisticAFTAdapter

    fit = LogLogisticAFTFitter()
    fit.fit(df_survival, duration_col="time", event_col="status")
    adapter = LifelinesLogLogisticAFTAdapter(fit, training_data=df_survival)

    t = adapter._prediction_time
    X5 = adapter.design_matrix_from_df(df_survival.head(5))
    our_pred = np.asarray(adapter.predict(adapter.coefficients(), X5))
    ll_pred = fit.predict_survival_function(
        df_survival[["x1", "x2"]].head(5), times=[t]
    ).values.flatten()

    np.testing.assert_allclose(our_pred, ll_pred, rtol=1e-6)


# ---------------------------------------------------------------------------
# 8. Lifelines GeneralizedGamma (bootstrap-only, compare against lifelines)
# ---------------------------------------------------------------------------

def test_generalized_gamma_predictions_match_lifelines(df_survival):
    """Adapter predict() should agree with lifelines predict_survival_function."""
    from lifelines import GeneralizedGammaRegressionFitter
    from pymargins._adapters.lifelines_generalized_gamma import LifelinesGeneralizedGammaAdapter

    fit = GeneralizedGammaRegressionFitter()
    fit.fit(df_survival, duration_col="time", event_col="status")
    adapter = LifelinesGeneralizedGammaAdapter(fit, training_data=df_survival)

    t = adapter._prediction_time
    X5 = adapter.design_matrix_from_df(df_survival.head(5))
    our_pred = np.asarray(adapter.predict(adapter.coefficients(), X5))
    ll_pred = fit.predict_survival_function(
        df_survival[["x1", "x2"]].head(5), times=[t]
    ).values.flatten()

    np.testing.assert_allclose(our_pred, ll_pred, rtol=1e-4)


# ---------------------------------------------------------------------------
# 9. Lifelines PiecewiseExponential (bootstrap-only, compare against lifelines)
# ---------------------------------------------------------------------------

def test_piecewise_exponential_predictions_match_lifelines(df_survival):
    """Adapter predict() should agree with lifelines predict_survival_function."""
    from lifelines import PiecewiseExponentialRegressionFitter
    from pymargins._adapters.lifelines_piecewise_exponential import LifelinesPiecewiseExponentialAdapter

    fit = PiecewiseExponentialRegressionFitter(breakpoints=[1, 3])
    fit.fit(df_survival, duration_col="time", event_col="status")
    adapter = LifelinesPiecewiseExponentialAdapter(fit, training_data=df_survival)

    t = adapter._prediction_time
    X5 = adapter.design_matrix_from_df(df_survival.head(5))
    our_pred = np.asarray(adapter.predict(adapter.coefficients(), X5))
    ll_pred = fit.predict_survival_function(
        df_survival[["x1", "x2"]].head(5), times=[t]
    ).values.flatten()

    np.testing.assert_allclose(our_pred, ll_pred, rtol=1e-4)


# ---------------------------------------------------------------------------
# 10. Lifelines CRCSpline (bootstrap-only, compare against lifelines)
# ---------------------------------------------------------------------------

def test_crc_spline_predictions_match_lifelines():
    """Adapter predict() should agree with lifelines predict_survival_function."""
    from lifelines import CRCSplineFitter
    from pymargins._adapters.lifelines_crc_spline import LifelinesCRCSplineAdapter

    rng = np.random.default_rng(42)
    n = 200
    df = pd.DataFrame({
        "x1": rng.standard_normal(n),
        "x2": rng.standard_normal(n),
    })
    hazard = np.exp(0.5 + 0.3 * df["x1"] - 0.2 * df["x2"])
    df["T"] = rng.exponential(1.0 / hazard)
    df["E"] = (rng.random(n) < 0.8).astype(int)

    fit = CRCSplineFitter(n_baseline_knots=3)
    fit.fit(
        df, duration_col="T", event_col="E",
        regressors={"beta_": "x1 + x2", "gamma0_": "1", "gamma1_": "1", "gamma2_": "1"}
    )
    adapter = LifelinesCRCSplineAdapter(fit, training_data=df)

    t = adapter._prediction_time
    X5 = adapter.design_matrix_from_df(df.head(5))
    our_pred = np.asarray(adapter.predict(adapter.coefficients(), X5))
    ll_pred = fit.predict_survival_function(
        df[["x1", "x2"]].head(5), times=[t]
    ).values.flatten()

    np.testing.assert_allclose(our_pred, ll_pred, rtol=1e-4)


# ---------------------------------------------------------------------------
# 11. Lifelines AalenAdditive (bootstrap-only, compare against lifelines)
# ---------------------------------------------------------------------------

def test_aalen_additive_predictions_match_lifelines(df_survival):
    """Adapter predict() should agree with lifelines predict_survival_function."""
    from lifelines import AalenAdditiveFitter
    from pymargins._adapters.lifelines_aalen_additive import LifelinesAalenAdditiveAdapter

    fit = AalenAdditiveFitter()
    fit.fit(df_survival, duration_col="time", event_col="status")
    adapter = LifelinesAalenAdditiveAdapter(fit, training_data=df_survival)

    t = adapter._prediction_time
    X5 = adapter.design_matrix_from_df(df_survival.head(5))
    our_pred = np.asarray(adapter.predict(adapter.coefficients(), X5))
    # AalenAdditiveFitter ignores times= and returns all observed times;
    # extract the row closest to prediction_time.
    ll_pred_full = fit.predict_survival_function(df_survival[["x1", "x2"]].head(5), times=[t])
    idx = ll_pred_full.index.get_indexer([t], method="nearest")[0]
    ll_pred = ll_pred_full.iloc[idx].values

    np.testing.assert_allclose(our_pred, ll_pred, rtol=1e-4)


# ---------------------------------------------------------------------------
# 12. Lifelines CRCSplineHR (hazard-ratio scale)
# ---------------------------------------------------------------------------

def test_crc_spline_hr_predictions_match_analytical():
    """HR = exp(X @ beta_beta) should match manual computation."""
    from lifelines import CRCSplineFitter
    from pymargins._adapters.lifelines_crc_spline_hr import LifelinesCRCSplineHRAdapter

    rng = np.random.default_rng(42)
    n = 200
    df = pd.DataFrame({
        "x1": rng.standard_normal(n),
        "x2": rng.standard_normal(n),
    })
    hazard = np.exp(0.5 + 0.3 * df["x1"] - 0.2 * df["x2"])
    df["T"] = rng.exponential(1.0 / hazard)
    df["E"] = (rng.random(n) < 0.8).astype(int)

    fit = CRCSplineFitter(n_baseline_knots=3)
    fit.fit(
        df, duration_col="T", event_col="E",
        regressors={"beta_": "x1 + x2", "gamma0_": "1", "gamma1_": "1", "gamma2_": "1"}
    )
    adapter = LifelinesCRCSplineHRAdapter(fit, training_data=df)

    X5 = np.asarray(adapter.design_matrix_from_df(df.head(5)))
    pred = np.asarray(adapter.predict(adapter.coefficients(), X5))

    beta = fit.params_.loc["beta_"].values
    manual = np.exp(X5 @ beta)

    np.testing.assert_allclose(pred, manual, rtol=1e-6)


# ---------------------------------------------------------------------------
# 13. Lifelines CoxTimeVarying partial-hazard AME
# ---------------------------------------------------------------------------

def test_cox_timevarying_ame_matches_analytical():
    """AME on partial-hazard scale should match mean(beta * exp((X - X_mean) @ beta))."""
    from lifelines import CoxTimeVaryingFitter
    from pymargins._adapters.lifelines_coxtimevarying import LifelinesCoxTimeVaryingAdapter

    rng = np.random.default_rng(42)
    n = 200
    df = pd.DataFrame({
        "x1": rng.standard_normal(n),
        "x2": rng.standard_normal(n),
    })
    hazard = np.exp(0.5 + 0.3 * df["x1"] - 0.2 * df["x2"])
    T = rng.exponential(1.0 / hazard)
    E = (rng.random(n) < 0.8).astype(int)
    df["id"] = np.arange(n)
    df["start"] = 0.0
    df["stop"] = T
    df["E"] = E

    fit = CoxTimeVaryingFitter(penalizer=0.1)
    fit.fit(df, id_col="id", start_col="start", stop_col="stop", event_col="E")
    adapter = LifelinesCoxTimeVaryingAdapter(fit, training_data=df)
    m = Margins(fit, adapter=adapter, at="overall", method="delta")

    res_x1 = m.dydx("x1")
    res_x2 = m.dydx("x2")

    beta = fit.params_.values
    X = df[["x1", "x2"]].values
    x_mean = fit._norm_mean.values if hasattr(fit, "_norm_mean") else np.zeros(2)
    pred_all = np.exp((X - x_mean) @ beta)
    manual_ame_x1 = np.mean(beta[0] * pred_all)
    manual_ame_x2 = np.mean(beta[1] * pred_all)

    np.testing.assert_allclose(float(res_x1.estimate), manual_ame_x1, rtol=1e-4)
    np.testing.assert_allclose(float(res_x2.estimate), manual_ame_x2, rtol=1e-4)


# ---------------------------------------------------------------------------
# 14. Lifelines CoxTimeVarying survival-probability scale
# ---------------------------------------------------------------------------

def test_cox_timevarying_survival_predictions_match_manual():
    """S(t|x) = S_0(t) ^ PH(x) should match manual computation."""
    from lifelines import CoxTimeVaryingFitter
    from pymargins._adapters.lifelines_cox_timevarying import LifelinesCoxTimeVaryingSurvivalAdapter

    rng = np.random.default_rng(42)
    n = 200
    df = pd.DataFrame({
        "x1": rng.standard_normal(n),
        "x2": rng.standard_normal(n),
    })
    hazard = np.exp(0.5 + 0.3 * df["x1"] - 0.2 * df["x2"])
    T = rng.exponential(1.0 / hazard)
    E = (rng.random(n) < 0.8).astype(int)
    df["id"] = np.arange(n)
    df["start"] = 0.0
    df["stop"] = T
    df["E"] = E

    fit = CoxTimeVaryingFitter(penalizer=0.1)
    fit.fit(df, id_col="id", start_col="start", stop_col="stop", event_col="E")
    adapter = LifelinesCoxTimeVaryingSurvivalAdapter(fit, training_data=df)

    t = adapter._prediction_time
    X5 = adapter.design_matrix_from_df(df.head(5))
    pred = np.asarray(adapter.predict(adapter.coefficients(), X5))

    # Manual: S0(t) ^ PH(x)
    ph = fit.predict_partial_hazard(df[["x1", "x2"]].head(5)).values.flatten()
    S0 = fit.baseline_survival_
    col = S0.columns[0]
    times = S0.index.values
    surv = S0[col].values
    if times[0] > times[-1]:
        times = times[::-1]
        surv = surv[::-1]
    S0_t = float(np.interp(t, times, surv))
    manual = S0_t ** ph

    np.testing.assert_allclose(pred, manual, rtol=1e-4)
