# Reference implementation using R's marginaleffects package
#
# Replicates the analyses from williams_2012_demo.py.  These values serve
# as "ground truth" for correctness tests of pymargins.
#
# Notes on scale
# --------------
# - The original pymargins demo uses Margins.log_scale(), which reports
#   *contrasts* as risk ratios (p1/p0) with asymmetric CIs.
# - R marginaleffects defaults to probability differences for contrasts.
# - This script reports BOTH quantities so tests can verify whichever
#   scale pymargins is configured to return.
#
# Notes on "typical" values
# -------------------------
# - pymargins classifies agegrp as continuous (due to integer dtype) and
#   uses its median (3) for "typical" calculations.
# - R treats agegrp as a factor and uses its mode (4) by default.
# - To match pymargins exactly, this script explicitly sets agegrp = "3"
#   in datagrids that replicate "at = typical" computations.

library(marginaleffects)

# ---------------------------------------------------------------------------
# Load data (generated by Python script to ensure identical observations)
# ---------------------------------------------------------------------------
df <- read.csv("demo/williams_2012_data.csv")

# Ensure categorical variables are factors
df$black   <- factor(df$black)
df$female  <- factor(df$female)
df$agegrp  <- factor(df$agegrp)

# ---------------------------------------------------------------------------
# 1. Logit model
# ---------------------------------------------------------------------------
cat("======================================================================\n")
cat("1. LOGIT MODEL\n")
cat("======================================================================\n")
fit_logit <- glm(
  diabetes ~ black + female + agegrp + bmi + age,
  data = df,
  family = binomial(link = "logit")
)
print(summary(fit_logit))
cat("\n")

# ---------------------------------------------------------------------------
# 2. Adjusted Predictions at the Means (APM)
# ---------------------------------------------------------------------------
cat("======================================================================\n")
cat("2. ADJUSTED PREDICTIONS AT THE MEANS (APM)\n")
cat("   Stata: margins agegrp, atmeans  (pymargins uses median = 'typical')\n")
cat("======================================================================\n")
# Explicit agegrp = '3' matches pymargins' median treatment of agegrp
apm <- predictions(
  fit_logit,
  newdata = datagrid(model = fit_logit, agegrp = levels(df$agegrp), agegrp = "3", FUN_numeric = median)
)
# The datagrid above creates a grid over agegrp with other vars at typical values
# Actually, let me construct it more carefully: one row per agegrp, other vars fixed
apm_grid <- data.frame(
  agegrp = factor(1:6, levels = 1:6),
  black = factor(0, levels = c(0, 1)),
  female = factor(1, levels = c(0, 1)),
  bmi = median(df$bmi),
  age = median(df$age)
)
apm <- predictions(fit_logit, newdata = apm_grid)
print(apm[, c("agegrp", "estimate", "p.value", "conf.low", "conf.high")])
cat("\n")

# ---------------------------------------------------------------------------
# 3. Average Adjusted Predictions (AAP)
# ---------------------------------------------------------------------------
cat("======================================================================\n")
cat("3. AVERAGE ADJUSTED PREDICTIONS (AAP)\n")
cat("   Stata: margins agegrp\n")
cat("======================================================================\n")
# variables= creates counterfactual grid (set agegrp for ALL observations)
aap <- avg_predictions(
  fit_logit,
  variables = list(agegrp = levels(df$agegrp)),
  by = "agegrp"
)
print(aap[, c("agegrp", "estimate", "std.error", "statistic", "p.value", "conf.low", "conf.high")])
cat("\n")

# ---------------------------------------------------------------------------
# 4. Predictions at Representative Values
# ---------------------------------------------------------------------------
cat("======================================================================\n")
cat("4. PREDICTIONS AT REPRESENTATIVE VALUES\n")
cat("   Stata: margins, at(age=(20 50 70)) atmeans\n")
cat("======================================================================\n")
repr_grid <- data.frame(
  age = c(20, 50, 70),
  black = factor(0, levels = c(0, 1)),
  female = factor(1, levels = c(0, 1)),
  agegrp = factor(3, levels = 1:6),
  bmi = median(df$bmi)
)
repr_pred <- predictions(fit_logit, newdata = repr_grid)
print(repr_pred[, c("age", "estimate", "p.value", "conf.low", "conf.high")])
cat("\n")

# ---------------------------------------------------------------------------
# 5. Marginal Effects at the Means (MEM) — continuous
# ---------------------------------------------------------------------------
cat("======================================================================\n")
cat("5. MARGINAL EFFECTS AT THE MEANS (MEM) — age\n")
cat("   Stata: margins, dydx(age) atmeans\n")
cat("======================================================================\n")
mem_grid <- data.frame(
  black = factor(0, levels = c(0, 1)),
  female = factor(1, levels = c(0, 1)),
  agegrp = factor(3, levels = 1:6),
  bmi = median(df$bmi),
  age = median(df$age)
)
mem_age <- avg_slopes(fit_logit, variables = "age", newdata = mem_grid)
print(mem_age[, c("term", "estimate", "std.error", "statistic", "p.value", "conf.low", "conf.high")])
cat("\n")

# ---------------------------------------------------------------------------
# 6. Average Marginal Effects (AME) — continuous
# ---------------------------------------------------------------------------
cat("======================================================================\n")
cat("6. AVERAGE MARGINAL EFFECTS (AME) — age\n")
cat("   Stata: margins, dydx(age)\n")
cat("======================================================================\n")
ame_age <- avg_slopes(fit_logit, variables = "age")
print(ame_age[, c("term", "estimate", "std.error", "statistic", "p.value", "conf.low", "conf.high")])
cat("\n")

# ---------------------------------------------------------------------------
# 7. Discrete changes for dummy variables
# ---------------------------------------------------------------------------
cat("======================================================================\n")
cat("7. DISCRETE CHANGE (MARGINAL EFFECT) — black\n")
cat("   Stata: margins, dydx(black)\n")
cat("======================================================================\n")

# Probability difference (default)
disc_black_pd <- avg_comparisons(fit_logit, variables = "black")
cat("Probability difference:\n")
print(disc_black_pd[, c("term", "estimate", "std.error", "statistic", "p.value", "conf.low", "conf.high")])

# Risk ratio via ln-ratio + exp transform
disc_black_rr <- avg_comparisons(
  fit_logit,
  variables = "black",
  comparison = "lnratioavg",
  transform = exp
)
cat("\nRisk ratio (lnratioavg, exp transform):\n")
print(disc_black_rr[, c("term", "estimate", "p.value", "conf.low", "conf.high")])
cat("\n")

# ---------------------------------------------------------------------------
cat("----------------------------------------------------------------------\n")
cat("7b. DISCRETE CHANGE AT THE MEANS — female\n")
cat("    Stata: margins, dydx(female) atmeans\n")
cat("----------------------------------------------------------------------\n")

# Probability difference at typical values (agegrp = 3 to match pymargins)
disc_female_grid <- data.frame(
  black = factor(0, levels = c(0, 1)),
  female = factor(c(0, 1), levels = c(0, 1)),
  agegrp = factor(3, levels = 1:6),
  bmi = median(df$bmi),
  age = median(df$age)
)
disc_female_pd <- avg_comparisons(fit_logit, variables = "female", newdata = disc_female_grid)
cat("Probability difference at typical:\n")
print(disc_female_pd[, c("term", "estimate", "std.error", "statistic", "p.value", "conf.low", "conf.high")])

# Risk ratio at typical values
disc_female_rr <- avg_comparisons(
  fit_logit,
  variables = "female",
  newdata = disc_female_grid,
  comparison = "lnratioavg",
  transform = exp
)
cat("\nRisk ratio at typical (lnratioavg, exp transform):\n")
print(disc_female_rr[, c("term", "estimate", "p.value", "conf.low", "conf.high")])
cat("\n")

# ---------------------------------------------------------------------------
# 8. Marginal Effects at Representative Values (MER)
# ---------------------------------------------------------------------------
cat("======================================================================\n")
cat("8. MARGINAL EFFECTS AT REPRESENTATIVE VALUES (MER)\n")
cat("   Stata: margins, dydx(black) at(female=(0 1))\n")
cat("======================================================================\n")

# Counterfactual: set female = 0 for all observations
df_male <- df
df_male$female <- factor(0, levels = levels(df$female))
mer_male_pd <- avg_comparisons(fit_logit, variables = "black", newdata = df_male)
cat("MALES (female=0) — Probability difference:\n")
print(mer_male_pd[, c("term", "estimate", "std.error", "statistic", "p.value", "conf.low", "conf.high")])

mer_male_rr <- avg_comparisons(
  fit_logit,
  variables = "black",
  newdata = df_male,
  comparison = "lnratioavg",
  transform = exp
)
cat("\nMALES (female=0) — Risk ratio:\n")
print(mer_male_rr[, c("term", "estimate", "p.value", "conf.low", "conf.high")])

# Counterfactual: set female = 1 for all observations
df_female <- df
df_female$female <- factor(1, levels = levels(df$female))
mer_female_pd <- avg_comparisons(fit_logit, variables = "black", newdata = df_female)
cat("\nFEMALES (female=1) — Probability difference:\n")
print(mer_female_pd[, c("term", "estimate", "std.error", "statistic", "p.value", "conf.low", "conf.high")])

mer_female_rr <- avg_comparisons(
  fit_logit,
  variables = "black",
  newdata = df_female,
  comparison = "lnratioavg",
  transform = exp
)
cat("\nFEMALES (female=1) — Risk ratio:\n")
print(mer_female_rr[, c("term", "estimate", "p.value", "conf.low", "conf.high")])
cat("\n")

# ---------------------------------------------------------------------------
# 9. OLS model
# ---------------------------------------------------------------------------
cat("======================================================================\n")
cat("9. OLS MODEL\n")
cat("======================================================================\n")
fit_ols <- lm(bp ~ black + female + age + bmi, data = df)
print(summary(fit_ols))
cat("\n")

cat("MEM / AME of age in OLS model (should match coefficient):\n")
mem_ols <- avg_slopes(fit_ols, variables = "age", newdata = "mean")
cat("MEM:\n")
print(mem_ols[, c("term", "estimate", "std.error", "statistic", "p.value", "conf.low", "conf.high")])
name_ols <- avg_slopes(fit_ols, variables = "age")
cat("\nAME:\n")
print(name_ols[, c("term", "estimate", "std.error", "statistic", "p.value", "conf.low", "conf.high")])
cat("\n")

# ---------------------------------------------------------------------------
# Compact reference table
# ---------------------------------------------------------------------------
cat("======================================================================\n")
cat("REFERENCE TABLE — Point Estimates\n")
cat("======================================================================\n")

cat(sprintf("%-40s %12s\n", "Estimand", "Value"))
cat(paste(rep("-", 54), collapse = ""), "\n")

for (i in seq_len(nrow(apm))) {
  cat(sprintf("%-40s %12.4f\n", paste0("APM agegrp=", apm$agegrp[i]), apm$estimate[i]))
}
for (i in seq_len(nrow(aap))) {
  cat(sprintf("%-40s %12.4f\n", paste0("AAP agegrp=", aap$agegrp[i]), aap$estimate[i]))
}
for (i in seq_len(nrow(repr_pred))) {
  cat(sprintf("%-40s %12.4f\n", paste0("Repr age=", repr_pred$age[i]), repr_pred$estimate[i]))
}
cat(sprintf("%-40s %12.4f\n", "MEM age", mem_age$estimate[1]))
cat(sprintf("%-40s %12.4f\n", "AME age", ame_age$estimate[1]))
cat(sprintf("%-40s %12.4f\n", "Discrete black (prob diff)", disc_black_pd$estimate[1]))
cat(sprintf("%-40s %12.4f\n", "Discrete black (risk ratio)", disc_black_rr$estimate[1]))
cat(sprintf("%-40s %12.4f\n", "Discrete female atmeans (prob diff)", disc_female_pd$estimate[1]))
cat(sprintf("%-40s %12.4f\n", "Discrete female atmeans (risk ratio)", disc_female_rr$estimate[1]))
cat(sprintf("%-40s %12.4f\n", "MER black | female=0 (prob diff)", mer_male_pd$estimate[1]))
cat(sprintf("%-40s %12.4f\n", "MER black | female=0 (risk ratio)", mer_male_rr$estimate[1]))
cat(sprintf("%-40s %12.4f\n", "MER black | female=1 (prob diff)", mer_female_pd$estimate[1]))
cat(sprintf("%-40s %12.4f\n", "MER black | female=1 (risk ratio)", mer_female_rr$estimate[1]))
cat(sprintf("%-40s %12.4f\n", "OLS age coefficient", coef(fit_ols)["age"]))
cat("\n")
cat("R marginaleffects reference complete.\n")
